# Generated by Django 5.1.2 on 2025-12-31 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials_app', '0003_rename_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialsmilestone',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialssnapshot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__account_e4cba2_idx ON financials_app_accountsnapshot (account_id, recorded_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__account_e4cba2_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__recorde_616f7c_idx ON financials_app_accountsnapshot (recorded_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__recorde_616f7c_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__created_4b53ed_idx ON financials_app_accountsnapshot (created_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__created_4b53ed_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_878e1b_idx ON financials_app_cashflowentry (owner_id, entry_date);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_878e1b_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_4e0cbf_idx ON financials_app_cashflowentry (owner_id, entry_type, entry_date);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_4e0cbf_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_074bd0_idx ON financials_app_cashflowentry (owner_id, category);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_074bd0_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_d16388_idx ON financials_app_changelog (owner_id, created_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_d16388_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_17d1f7_idx ON financials_app_changelog (owner_id, change_type);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_17d1f7_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__snapsho_e385d1_idx ON financials_app_changelog (snapshot_to_id);",
            reverse_sql="DROP INDEX IF EXISTS financials__snapsho_e385d1_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_b8cd68_idx ON financials_app_financialaccount (owner_id, account_type);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_b8cd68_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_673deb_idx ON financials_app_financialaccount (owner_id, is_active);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_673deb_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_c816ef_idx ON financials_app_financialaccount (owner_id, created_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_c816ef_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_0d42c7_idx ON financials_app_financialsmilestone (owner_id, is_active);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_0d42c7_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_47f7f9_idx ON financials_app_financialsmilestone (owner_id, achieved_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_47f7f9_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS financials__owner_i_696648_idx ON financials_app_financialssnapshot (owner_id, recorded_at);",
            reverse_sql="DROP INDEX IF EXISTS financials__owner_i_696648_idx;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'uniq_group_owner_name'
                    ) THEN
                        ALTER TABLE financials_app_accountgroup 
                        ADD CONSTRAINT uniq_group_owner_name 
                        UNIQUE (owner_id, name);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE financials_app_accountgroup DROP CONSTRAINT IF EXISTS uniq_group_owner_name;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'uniq_snapshot_account_date'
                    ) THEN
                        ALTER TABLE financials_app_accountsnapshot 
                        ADD CONSTRAINT uniq_snapshot_account_date 
                        UNIQUE (account_id, recorded_at);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE financials_app_accountsnapshot DROP CONSTRAINT IF EXISTS uniq_snapshot_account_date;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'uniq_account_owner_name'
                    ) THEN
                        ALTER TABLE financials_app_financialaccount 
                        ADD CONSTRAINT uniq_account_owner_name 
                        UNIQUE (owner_id, name);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE financials_app_financialaccount DROP CONSTRAINT IF EXISTS uniq_account_owner_name;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'uniq_networth_owner_date'
                    ) THEN
                        ALTER TABLE financials_app_financialssnapshot 
                        ADD CONSTRAINT uniq_networth_owner_date 
                        UNIQUE (owner_id, recorded_at);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE financials_app_financialssnapshot DROP CONSTRAINT IF EXISTS uniq_networth_owner_date;",
        ),
    ]
