# Generated by Django 5.1.2 on 2026-01-03 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials_app', '0004_alter_changelog_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['account', 'recorded_at'], name='financials__account_e4cba2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['recorded_at'], name='financials__recorde_616f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['created_at'], name='financials__created_4b53ed_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['owner', 'entry_date'], name='financials__owner_i_878e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['owner', 'entry_type', 'entry_date'], name='financials__owner_i_4e0cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['owner', 'category'], name='financials__owner_i_074bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['owner', 'created_at'], name='financials__owner_i_d16388_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['owner', 'change_type'], name='financials__owner_i_17d1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['snapshot_to'], name='financials__snapsho_e385d1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['owner', 'account_type'], name='financials__owner_i_b8cd68_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['owner', 'is_active'], name='financials__owner_i_673deb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['owner', 'created_at'], name='financials__owner_i_c816ef_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsmilestone',
            index=models.Index(fields=['owner', 'is_active'], name='financials__owner_i_0d42c7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsmilestone',
            index=models.Index(fields=['owner', 'achieved_at'], name='financials__owner_i_47f7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialssnapshot',
            index=models.Index(fields=['owner', 'recorded_at'], name='financials__owner_i_696648_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_group_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='accountsnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'recorded_at'), name='uniq_snapshot_account_date'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_account_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='financialssnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'recorded_at'), name='uniq_networth_owner_date'),
        ),
    ]
