# Generated by Django 5.1.2 on 2026-01-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether email has been verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google user ID (sub)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_linked_at',
            field=models.DateTimeField(blank=True, help_text='When Google account was linked', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_usable_password',
            field=models.BooleanField(default=True, help_text='False if account was created via Google without password'),
        ),
    ]
