# Generated by Django 5.1.2 on 2025-12-29 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='teal', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Event categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_before', models.PositiveIntegerField(default=15)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_push', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['minutes_before'],
            },
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_at']},
        ),
        migrations.AlterModelOptions(
            name='eventoccurrence',
            options={'ordering': ['start_at']},
        ),
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='teal', max_length=20),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='teal', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='description_override',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='location_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='title_override',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['is_cancelled'], name='schedule_ap_is_canc_146f8f_idx'),
        ),
        migrations.AddField(
            model_name='eventattachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='schedule_app.event'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='schedule_app.eventcategory'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'start_at'], name='schedule_ap_calenda_1a665f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['priority'], name='schedule_ap_priorit_acb5ec_idx'),
        ),
        migrations.AddField(
            model_name='remindertemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_templates', to='schedule_app.event'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='schedule_app.remindertemplate'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['fired_at'], name='schedule_ap_fired_a_31727e_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_category_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='remindertemplate',
            constraint=models.UniqueConstraint(fields=('event', 'minutes_before'), name='uniq_reminder_event_minutes'),
        ),
    ]
