# Generated by Django 5.1.2 on 2026-01-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_enhanced_schema_3nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_immutable',
            field=models.BooleanField(default=False),
        ),
    ]
