# Generated by Django 5.1.2 on 2026-01-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_update_birthday_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='teal', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='teal', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='color',
            field=models.CharField(default='teal', max_length=255),
        ),
    ]
