# Generated by Django 5.1.2 on 2025-12-30 19:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'target_currency'], name='travel_app__base_cu_461275_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='uniq_exchange_rate_pair')],
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('activity', 'Activity'), ('free_time', 'Free Time'), ('other', 'Other')], default='activity', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel_app.itinerary')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('toiletries', 'Toiletries'), ('electronics', 'Electronics'), ('documents', 'Documents'), ('medications', 'Medications'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_packed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel_app.packinglist')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(help_text='2-letter ISO country code', max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('trip_type', models.CharField(choices=[('vacation', 'Vacation'), ('business', 'Business'), ('adventure', 'Adventure'), ('city_break', 'City Break'), ('beach', 'Beach'), ('road_trip', 'Road Trip'), ('backpacking', 'Backpacking')], default='vacation', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planning', max_length=20)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('budget_currency', models.CharField(default='USD', max_length=3)),
                ('actual_spend', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('budget_flights', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('budget_accommodation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('budget_food', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('budget_activities', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('budget_transport', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('budget_shopping', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('budget_other', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('color', models.CharField(default='#208585', max_length=7)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('calendar_event_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(help_text='2-letter ISO country code', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_goals', to=settings.AUTH_USER_MODEL)),
                ('linked_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achieved_goals', to='travel_app.trip')),
            ],
            options={
                'ordering': ['-priority', 'target_date'],
            },
        ),
        migrations.AddField(
            model_name='packinglist',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_list', to='travel_app.trip'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='travel_app.trip'),
        ),
        migrations.CreateModel(
            name='TripDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('flight', 'Flight Booking'), ('hotel', 'Hotel Booking'), ('rental', 'Car Rental'), ('activity', 'Activity Booking'), ('insurance', 'Travel Insurance'), ('other', 'Other')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel_app.trip')),
            ],
            options={
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12)),
                ('category', models.CharField(choices=[('flights', 'Flights'), ('accommodation', 'Accommodation'), ('food', 'Food & Dining'), ('activities', 'Activities'), ('transport', 'Local Transport'), ('shopping', 'Shopping'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('expense_date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('receipt_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel_app.trip')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['owner', 'status'], name='travel_app__owner_i_ddfc03_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['owner', 'start_date'], name='travel_app__owner_i_0a969f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['owner', 'is_archived'], name='travel_app__owner_i_e7b346_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='travel_app__start_d_1db745_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerary',
            constraint=models.UniqueConstraint(fields=('trip', 'day_number'), name='uniq_itinerary_trip_day'),
        ),
        migrations.AddIndex(
            model_name='tripdocument',
            index=models.Index(fields=['trip', 'document_type'], name='travel_app__trip_id_2fd658_idx'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['trip', 'category'], name='travel_app__trip_id_ec5dec_idx'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['trip', 'expense_date'], name='travel_app__trip_id_42689f_idx'),
        ),
    ]
