# Generated by Django 5.1.2 on 2025-12-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_profile_options_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='instagram',
        ),
    ]
