# Generated by Django 5.1.2 on 2026-01-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_backfill_birthday_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_picture_url',
            field=models.URLField(blank=True, help_text='Google profile picture URL', max_length=500),
        ),
    ]
