# Generated by Django 5.1.2 on 2025-12-30 18:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, help_text='Service provider name', max_length=200)),
                ('website_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('custom_cycle_days', models.PositiveIntegerField(blank=True, help_text='Days between charges for custom cycle', null=True)),
                ('normalized_monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monthly equivalent amount (auto-calculated)', max_digits=10)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField(db_index=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('streaming', 'Streaming & Entertainment'), ('software', 'Software & Apps'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('membership', 'Memberships'), ('financial', 'Financial Services'), ('health', 'Health & Fitness'), ('education', 'Education'), ('cloud', 'Cloud Services'), ('news', 'News & Media'), ('gaming', 'Gaming'), ('food', 'Food & Delivery'), ('productivity', 'Productivity'), ('security', 'Security'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Custom tags')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('is_essential', models.BooleanField(default=False, help_text='Mark as essential (not candidate for cancellation)')),
                ('auto_renew', models.BooleanField(default=True)),
                ('color', models.CharField(default='#208585', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('calendar_event_id', models.CharField(blank=True, db_index=True, help_text='Link to Calendar event for reminders', max_length=255)),
                ('reminder_days_before', models.PositiveIntegerField(default=3, help_text='Days before billing to send reminder')),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, help_text='External service ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_billing_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_increase', 'Price Increase'), ('unused', 'Unused Subscription'), ('upcoming_charge', 'Upcoming Charge'), ('annual_spike', 'Annual Spending Spike'), ('trial_ending', 'Trial Ending'), ('spend_threshold', 'Monthly Spend Threshold'), ('duplicate', 'Potential Duplicate'), ('renewal', 'Renewal Reminder')], db_index=True, max_length=20)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold value (e.g., % increase, $ amount, days)', max_digits=10, null=True)),
                ('threshold_days', models.PositiveIntegerField(blank=True, help_text='Days threshold (e.g., unused for X days)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='subscriptions_app.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('subscription_name', models.CharField(max_length=200)),
                ('trigger_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions_app.subscriptionalert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('charged_at', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API/Bank Sync'), ('import', 'Data Import'), ('auto', 'Auto-Generated')], default='manual', max_length=20)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Previous charge amount for comparison', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='subscriptions_app.subscription')),
            ],
            options={
                'ordering': ['-charged_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInsightSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('paused_count', models.PositiveIntegerField(default=0)),
                ('trial_count', models.PositiveIntegerField(default=0)),
                ('unused_count', models.PositiveIntegerField(default=0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('new_subscriptions', models.PositiveIntegerField(default=0)),
                ('cancelled_subscriptions', models.PositiveIntegerField(default=0)),
                ('price_increases', models.PositiveIntegerField(default=0)),
                ('spend_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spend_change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsageSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('manual_checkin', 'Manual Check-in'), ('auto_detected', 'Auto-Detected'), ('calendar_event', 'Calendar Event'), ('inferred', 'Inferred')], default='manual_checkin', max_length=20)),
                ('last_used_at', models.DateField(blank=True, help_text='Date subscription was last used', null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Confidence in the usage signal (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_signals', to='subscriptions_app.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_3d70d9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'next_billing_date'], name='subscriptio_user_id_b2c5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'category'], name='subscriptio_user_id_bc3b04_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_3386f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_subscription_user_name'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_870be6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['user', 'alert_type'], name='subscriptio_user_id_1ae3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalertevent',
            index=models.Index(fields=['alert', 'triggered_at'], name='subscriptio_alert_i_099681_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalertevent',
            index=models.Index(fields=['is_read', 'is_dismissed'], name='subscriptio_is_read_dd7309_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['subscription', 'charged_at'], name='subscriptio_subscri_4103ab_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['charged_at'], name='subscriptio_charged_d6d78d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninsightsnapshot',
            index=models.Index(fields=['user', 'month'], name='subscriptio_user_id_dcd22c_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninsightsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='uniq_insight_user_month'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusagesignal',
            index=models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_0c7ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusagesignal',
            index=models.Index(fields=['subscription', 'last_used_at'], name='subscriptio_subscri_7c0515_idx'),
        ),
    ]
