# Generated by Django 5.1.2 on 2026-01-03 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions_app', '0001_initial'),
    ]

    operations = [
        # Rename old columns to new names
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                RENAME COLUMN cost TO amount;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                RENAME COLUMN next_payment_date TO next_billing_date;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Drop old columns that are no longer needed
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                DROP COLUMN IF EXISTS cancellation_url,
                DROP COLUMN IF EXISTS is_variable_cost,
                DROP COLUMN IF EXISTS my_share,
                DROP COLUMN IF EXISTS normalized_monthly_cost,
                DROP COLUMN IF EXISTS reminder_days,
                DROP COLUMN IF EXISTS payment_method_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Add all potentially missing columns to subscriptions_app_subscription
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS provider VARCHAR(200) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS website_url VARCHAR(200) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS custom_cycle_days INTEGER;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS normalized_monthly_amount NUMERIC(10, 2) DEFAULT 0 NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS trial_end_date DATE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS cancellation_date DATE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS is_essential BOOLEAN DEFAULT FALSE NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN DEFAULT TRUE NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS color VARCHAR(7) DEFAULT '#208585' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS icon VARCHAR(50) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS logo_url VARCHAR(200) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS calendar_event_id VARCHAR(255) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS reminder_days_before INTEGER DEFAULT 3 NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS payment_method VARCHAR(100) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS last_payment_date DATE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS last_payment_amount NUMERIC(10, 2);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_app_subscription
                ADD COLUMN IF NOT EXISTS external_id VARCHAR(255) DEFAULT '' NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
