# Generated by Django 5.1.2 on 2026-01-03 07:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_app', '0002_add_normalized_monthly_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create SubscriptionCharge table
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('charged_at', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API/Bank Sync'), ('import', 'Data Import'), ('auto', 'Auto-Generated')], default='manual', max_length=20)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Previous charge amount for comparison', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='subscriptions_app.subscription')),
            ],
            options={
                'ordering': ['-charged_at', '-created_at'],
            },
        ),
        # Create SubscriptionUsageSignal table
        migrations.CreateModel(
            name='SubscriptionUsageSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('manual_checkin', 'Manual Check-in'), ('auto_detected', 'Auto-Detected'), ('calendar_event', 'Calendar Event'), ('inferred', 'Inferred')], default='manual_checkin', max_length=20)),
                ('last_used_at', models.DateField(blank=True, help_text='Date subscription was last used', null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Confidence in the usage signal (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_signals', to='subscriptions_app.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Create SubscriptionAlert table
        migrations.CreateModel(
            name='SubscriptionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_increase', 'Price Increase'), ('unused', 'Unused Subscription'), ('upcoming_charge', 'Upcoming Charge'), ('annual_spike', 'Annual Spending Spike'), ('trial_ending', 'Trial Ending'), ('spend_threshold', 'Monthly Spend Threshold'), ('duplicate', 'Potential Duplicate'), ('renewal', 'Renewal Reminder')], db_index=True, max_length=20)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold value (e.g., % increase, $ amount, days)', max_digits=10, null=True)),
                ('threshold_days', models.PositiveIntegerField(blank=True, help_text='Days threshold (e.g., unused for X days)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='subscriptions_app.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Create SubscriptionAlertEvent table
        migrations.CreateModel(
            name='SubscriptionAlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('subscription_name', models.CharField(max_length=200)),
                ('trigger_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions_app.subscriptionalert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        # Create SubscriptionInsightSnapshot table
        migrations.CreateModel(
            name='SubscriptionInsightSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('paused_count', models.PositiveIntegerField(default=0)),
                ('trial_count', models.PositiveIntegerField(default=0)),
                ('unused_count', models.PositiveIntegerField(default=0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('new_subscriptions', models.PositiveIntegerField(default=0)),
                ('cancelled_subscriptions', models.PositiveIntegerField(default=0)),
                ('price_increases', models.PositiveIntegerField(default=0)),
                ('spend_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spend_change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        # Add indexes for SubscriptionCharge
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['subscription', 'charged_at'], name='subscriptio_subscri_4103ab_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['charged_at'], name='subscriptio_charged_d6d78d_idx'),
        ),
        # Add indexes for SubscriptionUsageSignal
        migrations.AddIndex(
            model_name='subscriptionusagesignal',
            index=models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_0c7ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusagesignal',
            index=models.Index(fields=['subscription', 'last_used_at'], name='subscriptio_subscri_7c0515_idx'),
        ),
        # Add indexes for SubscriptionAlert
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_870be6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalert',
            index=models.Index(fields=['user', 'alert_type'], name='subscriptio_user_id_1ae3d5_idx'),
        ),
        # Add indexes for SubscriptionAlertEvent
        migrations.AddIndex(
            model_name='subscriptionalertevent',
            index=models.Index(fields=['alert', 'triggered_at'], name='subscriptio_alert_i_099681_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalertevent',
            index=models.Index(fields=['is_read', 'is_dismissed'], name='subscriptio_is_read_dd7309_idx'),
        ),
        # Add indexes for SubscriptionInsightSnapshot
        migrations.AddIndex(
            model_name='subscriptioninsightsnapshot',
            index=models.Index(fields=['user', 'month'], name='subscriptio_user_id_dcd22c_idx'),
        ),
        # Add constraints
        migrations.AddConstraint(
            model_name='subscriptioninsightsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='uniq_insight_user_month'),
        ),
    ]
