export const iconMap = {
  Overcast: "bi bi-cloud-fill",
  Fog: "bi bi-cloud-haze-fill",
  "Depositing rime fog": "bi bi-cloud-haze-fill",
  Windy: "bi bi-wind",
  Sunrise: "bi bi-sunrise-fill",
  Sunset: "bi bi-sunset-fill",
  "Drizzle: Light": "bi bi-cloud-drizzle-fill",
  "Drizzle: Moderate": "bi bi-cloud-drizzle-fill",
  "Drizzle: Dense": "bi bi-cloud-drizzle-fill",
  "Freezing drizzle: Light": "bi bi-cloud-sleet-fill",
  "Freezing drizzle: Dense": "bi bi-cloud-sleet-fill",
  "Rain: Slight": "bi bi-cloud-rain-fill",
  "Rain: Moderate": "bi bi-cloud-rain-fill",
  "Rain: Heavy": "bi bi-cloud-rain-heavy-fill",
  "Freezing rain: Light": "bi bi-cloud-sleet-fill",
  "Freezing rain: Heavy": "bi bi-cloud-sleet-fill",
  "Snow fall: Slight": "bi bi-cloud-snow-fill",
  "Snow fall: Moderate": "bi bi-cloud-snow-fill",
  "Snow fall: Heavy": "bi bi-cloud-snow-fill",
  "Snow grains": "bi bi-cloud-snow-fill",
  "Rain showers: Slight": "bi bi-cloud-rain-fill",
  "Rain showers: Moderate": "bi bi-cloud-rain-fill",
  "Rain showers: Violent": "bi bi-cloud-lightning-rain-fill",
  "Snow showers: Slight": "bi bi-cloud-snow-fill",
  "Snow showers: Heavy": "bi bi-cloud-snow-fill",
  "Thunderstorm: Slight or moderate": "bi bi-cloud-lightning-fill",
  "Thunderstorm with slight hail": "bi bi-cloud-lightning-rain-fill",
  "Thunderstorm with heavy hail": "bi bi-cloud-lightning-rain-fill",
  "Clear sky": {
    day: "bi bi-sun-fill",
    night: "bi bi-moon-stars-fill",
  },
  "Mainly clear": {
    day: "bi bi-sun-fill",
    night: "bi bi-moon-stars-fill",
  },
  "Partly cloudy": {
    day: "bi bi-cloud-sun-fill",
    night: "bi bi-cloud-moon-fill",
  },
};

export const videoMap = {
  Fog: "/videos/foggy.mp4",
  "Depositing rime fog": "/videos/foggy.mp4",
  Windy: "/videos/windy.mp4",
  "Drizzle: Light": "/videos/slight-rain.mp4",
  "Drizzle: Moderate": "/videos/slight-rain.mp4",
  "Drizzle: Dense": {
    day: "/videos/day-rainy.mp4",
    night: "/videos/night-rainy.mp4",
  },
  "Freezing drizzle: Light": "/videos/snowy.mp4",
  "Freezing drizzle: Dense": "/videos/snowy.mp4",
  "Rain: Slight": "/videos/slight-rain.mp4",
  "Rain: Moderate": {
    day: "/videos/day-rainy.mp4",
    night: "/videos/night-rainy.mp4",
  },
  "Rain: Heavy": {
    day: "/videos/day-rainy.mp4",
    night: "/videos/night-rainy.mp4",
  },
  "Freezing rain: Light": "/videos/snowy.mp4",
  "Freezing rain: Heavy": "/videos/snowy.mp4",
  "Snow fall: Slight": "/videos/snowy.mp4",
  "Snow fall: Moderate": "/videos/snowy.mp4",
  "Snow fall: Heavy": "/videos/snowy.mp4",
  "Rain showers: Slight": "/videos/slight-rain.mp4",
  "Rain showers: Moderate": {
    day: "/videos/day-rainy.mp4",
    night: "/videos/night-rainy.mp4",
  },
  "Rain showers: Violent": "/videos/thunderstorm.mp4",
  "Thunderstorm: Slight or moderate": "/videos/thunderstorm.mp4",
  "Thunderstorm with slight hail": "/videos/thunderstorm.mp4",
  "Thunderstorm with heavy hail": "/videos/thunderstorm.mp4",
  "Clear sky": {
    day: "/videos/sunny-sky.mp4",
    night: "/videos/night-sky.mp4",
  },
  "Mainly clear": {
    day: "/videos/sunny-sky.mp4",
    night: "/videos/night-sky.mp4",
  },
  "Partly cloudy": {
    day: "/videos/partly-cloudy.mp4",
    night: "/videos/cloudy-night.mp4",
  },
  Overcast: {
    day: "/videos/cloudy.mp4",
    night: "/videos/cloudy-night.mp4",
  },
  default: {
    clear: "",
    night: "",
  },
};
