import { weatherImgs } from "./images";

export const iconMap = {
  Overcast: weatherImgs.cloudy,
  Fog: weatherImgs.fog,
  "Depositing rime fog": weatherImgs.fog,
  "Drizzle: Light": weatherImgs.slight_rain,
  "Drizzle: Moderate": weatherImgs.slight_rain,
  "Drizzle: Dense": weatherImgs.rainy,
  "Freezing drizzle: Light": weatherImgs.snowy,
  "Freezing drizzle: Dense": weatherImgs.snowy,
  "Rain: Slight": weatherImgs.slight_rain,
  "Rain: Moderate": weatherImgs.rainy,
  "Rain: Heavy": weatherImgs.rainy,
  "Freezing rain: Light": weatherImgs.snowy,
  "Freezing rain: Heavy": weatherImgs.snowy,
  "Snow fall: Slight": weatherImgs.snowy,
  "Snow fall: Moderate": weatherImgs.snowy,
  "Snow fall: Heavy": weatherImgs.snowy,
  "Snow grains": weatherImgs.snowy,
  "Rain showers: Slight": weatherImgs.slight_rain,
  "Rain showers: Moderate": weatherImgs.rainy,
  "Rain showers: Violent": weatherImgs.storm,
  "Snow showers: Slight": weatherImgs.snowy,
  "Snow showers: Heavy": weatherImgs.snowy,
  "Thunderstorm: Slight or moderate": weatherImgs.storm,
  "Thunderstorm with slight hail": weatherImgs.storm,
  "Thunderstorm with heavy hail": weatherImgs.storm,
  "Clear sky": {
    day: weatherImgs.sunny,
    night: weatherImgs.clear_night,
  },
  "Mainly clear": {
    day: weatherImgs.sunny,
    night: weatherImgs.clear_night,
  },
  "Partly cloudy": {
    day: weatherImgs.partly_cloudy,
    night: weatherImgs.cloudy_night,
  },
};

export const videoMap = {
  Fog: "/videos/fog.mp4",
  "Drizzle: Light": "/videos/slight-rain.mp4",
  "Drizzle: Moderate": "/videos/slight-rain.mp4",
  "Drizzle: Dense": "/videos/rainy.mp4",
  "Freezing drizzle: Light": "/videos/snowy.mp4",
  "Freezing drizzle: Dense": "/videos/snowy.mp4",
  "Rain: Slight": "/videos/slight-rain.mp4",
  "Rain: Moderate": "/videos/rainy.mp4",
  "Rain: Heavy": "/videos/rainy.mp4",
  "Freezing rain: Light": "/videos/snowy.mp4",
  "Freezing rain: Heavy": "/videos/snowy.mp4",
  "Snow fall: Slight": "/videos/snowy.mp4",
  "Snow fall: Moderate": "/videos/snowy.mp4",
  "Snow fall: Heavy": "/videos/snowy.mp4",
  "Rain showers: Slight": "/videos/slight-rain.mp4",
  "Rain showers: Moderate": "/videos/rainy.mp4",
  "Rain showers: Violent": "/videos/thunderstorm.mp4",
  "Thunderstorm: Slight or moderate": "/videos/thunderstorm.mp4",
  "Thunderstorm with slight hail": "/videos/thunderstorm.mp4",
  "Thunderstorm with heavy hail": "/videos/thunderstorm.mp4",
  "Clear sky": {
    day: "/videos/sunny-sky.mp4",
    night: "/videos/night-sky.mp4",
  },
  "Mainly clear": {
    day: "/videos/sunny-sky.mp4",
    night: "/videos/night-sky.mp4",
  },
  "Partly cloudy": {
    day: "/videos/partly-cloudy.mp4",
    night: "/videos/cloudy-night.mp4",
  },
  Overcast: {
    day: "/videos/cloudy.mp4",
    night: "/videos/cloudy-night.mp4",
  },
  default: {
    clear: "",
    night: "",
  },
};
