# Generated by Django 5.1.2 on 2025-12-30 17:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('investment', 'Investment'), ('debt', 'Debt/Liability'), ('asset', 'Physical Asset')], db_index=True, max_length=20)),
                ('subtype', models.CharField(blank=True, choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('cash_on_hand', 'Cash on Hand'), ('emergency_fund', 'Emergency Fund'), ('brokerage', 'Brokerage Account'), ('401k', '401(k)'), ('ira', 'IRA'), ('roth_ira', 'Roth IRA'), ('hsa', 'HSA'), ('crypto', 'Cryptocurrency'), ('other_investment', 'Other Investment'), ('credit_card', 'Credit Card'), ('student_loan', 'Student Loan'), ('mortgage', 'Mortgage'), ('auto_loan', 'Auto Loan'), ('personal_loan', 'Personal Loan'), ('medical_debt', 'Medical Debt'), ('other_debt', 'Other Debt'), ('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('jewelry', 'Jewelry/Valuables'), ('collectibles', 'Collectibles'), ('other_asset', 'Other Asset')], max_length=30)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API Connected')], default='manual', max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('apr', models.DecimalField(blank=True, decimal_places=3, help_text='Annual Percentage Rate for debt accounts', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit for credit cards', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly payment for debt', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('color', models.CharField(default='#208585', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from net worth calculations but preserve history')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment_income', 'Investment Income'), ('rental_income', 'Rental Income'), ('bonus', 'Bonus'), ('other_income', 'Other Income'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('food', 'Food & Dining'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('debt_payment', 'Debt Payment'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('personal', 'Personal Care'), ('education', 'Education'), ('travel', 'Travel'), ('savings', 'Savings Transfer'), ('taxes', 'Taxes'), ('gifts', 'Gifts & Donations'), ('other_expense', 'Other Expense')], db_index=True, max_length=30)),
                ('entry_date', models.DateField(db_index=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE for recurring entries', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_entries', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_entries', to='networth_app.financialaccount')),
            ],
            options={
                'verbose_name_plural': 'Cash flow entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, help_text='Account value/balance at this snapshot', max_digits=15)),
                ('available_credit', models.DecimalField(blank=True, decimal_places=2, help_text='Available credit for credit cards', max_digits=15, null=True)),
                ('recorded_at', models.DateField(db_index=True, help_text='The date this value represents')),
                ('source', models.CharField(choices=[('manual_entry', 'Manual Entry'), ('api_sync', 'API Sync'), ('import', 'Data Import'), ('adjustment', 'Adjustment')], default='manual_entry', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_snapshots', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='networth_app.financialaccount')),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#208585', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to=settings.AUTH_USER_MODEL)),
                ('accounts', models.ManyToManyField(blank=True, related_name='groups', to='networth_app.financialaccount')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetWorthMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('milestone_type', models.CharField(choices=[('net_worth', 'Net Worth Target'), ('savings', 'Savings Target'), ('debt_payoff', 'Debt Payoff'), ('investment', 'Investment Target'), ('emergency_fund', 'Emergency Fund'), ('custom', 'Custom Goal')], default='net_worth', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_at', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#00fe93', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_celebrated', models.BooleanField(default=False, help_text='User has acknowledged milestone achievement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='networth_app.financialaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'target_amount'],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_worth', models.DecimalField(decimal_places=2, help_text='Total Assets - Total Liabilities', max_digits=15)),
                ('cash_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('investment_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('asset_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('debt_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('recorded_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('streaming', 'Streaming & Entertainment'), ('software', 'Software & Apps'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('membership', 'Memberships'), ('financial', 'Financial Services'), ('health', 'Health & Fitness'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(default='#208585', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_essential', models.BooleanField(default=False, help_text='Mark as essential expense')),
                ('auto_renew', models.BooleanField(default=True)),
                ('calendar_event_id', models.CharField(blank=True, help_text='Link to Calendar event for reminders', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(blank=True, help_text='Account used to pay this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_paid', to='networth_app.financialaccount')),
            ],
            options={
                'ordering': ['next_billing_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('account_added', 'New Account Added'), ('account_removed', 'Account Removed'), ('value_increase', 'Value Increased'), ('value_decrease', 'Value Decreased'), ('milestone_achieved', 'Milestone Achieved'), ('debt_paid_off', 'Debt Paid Off'), ('subscription_added', 'Subscription Added'), ('subscription_cancelled', 'Subscription Cancelled'), ('net_worth_increase', 'Net Worth Increased'), ('net_worth_decrease', 'Net Worth Decreased')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('amount_change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('importance', models.PositiveSmallIntegerField(default=5, help_text='1-10 scale, higher = more important')),
                ('is_positive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_changes', to=settings.AUTH_USER_MODEL)),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='networth_app.financialaccount')),
                ('related_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='networth_app.networthmilestone')),
                ('snapshot_from', models.ForeignKey(blank=True, help_text='Previous snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='networth_app.networthsnapshot')),
                ('snapshot_to', models.ForeignKey(help_text='Current snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='networth_app.networthsnapshot')),
                ('related_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='networth_app.subscription')),
            ],
            options={
                'ordering': ['-created_at', '-importance'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['owner', 'account_type'], name='networth_ap_owner_i_466179_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['owner', 'is_active'], name='networth_ap_owner_i_48da52_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['owner', 'created_at'], name='networth_ap_owner_i_6ab814_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_account_owner_name'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['owner', 'entry_date'], name='networth_ap_owner_i_2b7aff_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['owner', 'entry_type', 'entry_date'], name='networth_ap_owner_i_11b625_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['owner', 'category'], name='networth_ap_owner_i_7186a9_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['account', 'recorded_at'], name='networth_ap_account_5b69f2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['recorded_at'], name='networth_ap_recorde_b3271f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['created_at'], name='networth_ap_created_1f2b28_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountsnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'recorded_at'), name='uniq_snapshot_account_date'),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_group_owner_name'),
        ),
        migrations.AddIndex(
            model_name='networthmilestone',
            index=models.Index(fields=['owner', 'is_active'], name='networth_ap_owner_i_f52012_idx'),
        ),
        migrations.AddIndex(
            model_name='networthmilestone',
            index=models.Index(fields=['owner', 'achieved_at'], name='networth_ap_owner_i_854694_idx'),
        ),
        migrations.AddIndex(
            model_name='networthsnapshot',
            index=models.Index(fields=['owner', 'recorded_at'], name='networth_ap_owner_i_22b0a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='networthsnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'recorded_at'), name='uniq_networth_owner_date'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'is_active'], name='networth_ap_owner_i_0a671c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'next_billing_date'], name='networth_ap_owner_i_c2eaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['category'], name='networth_ap_categor_88cd40_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['owner', 'created_at'], name='networth_ap_owner_i_b2ecc6_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['owner', 'change_type'], name='networth_ap_owner_i_d34b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['snapshot_to'], name='networth_ap_snapsho_c7d8d2_idx'),
        ),
    ]
